[nfs]
172.31.19.7 ansible_ssh_user='ec2-user'

[webservers]
172.31.21.196 ansible_ssh_user='ec2-user'
172.31.31.192 ansible_ssh_user='ec2-user'

[db]
172.31.30.22 ansible_ssh_user='ubuntu' 

[lb]
172.31.23.92 ansible_ssh_user='ubuntu'